### ISSUE TITLE
Home page Image is not Flexible(Responsive) in Mobile View

### ISSUE THREAD

**Issue by TheBaljitSingh** [TheBaljitSingh/Apna-Blog-Frontend#1]
- make sure Home page image is flexible in mobile.
- if you want to add content for home page it would be appreciated.

**Comment by mpa-LHutchinson** [comment]
Hi @TheBaljitSingh, can you assign this issue to me and give it the "hacktoberfest" label, I'll get working on it as soon as I can today.

**Comment by TheBaljitSingh** [comment]
i have assigned to you.

**Comment by mpa-LHutchinson** [comment]
@TheBaljitSingh I updated this with #2

**Comment by TheBaljitSingh** [comment]
Can you Improve the color of Navbar.
Like for Default it should  Light  and for Dark as it deployed

**Comment by TheBaljitSingh** [comment]
Remove the Sign up and login on homepage because it is mentioned in the top right Navbar

**Comment by mpa-LHutchinson** [comment]
Ok, I'll make those changes tomorrow when I get the chance. And just to be clear, how do you want the navbar to be improved exactly?

**Comment by kushaltalati** [comment]
@TheBaljitSingh I can make changes and make the background image responsive, assign me this task under hactoberfest tag.

**Comment by TheBaljitSingh** [comment]
Assigned

**Comment by mpa-LHutchinson** [comment]
@TheBaljitSingh I removed the buttons for #2
