### ISSUE TITLE
Add 'Or with Horizontal line' between 'login' button and 'sign in with Google' button on Login Page. Refer image

### ISSUE THREAD

**Issue by TheBaljitSingh** [TheBaljitSingh/Apna-Blog-Frontend#8]
Image reference
![Screenshot_2024-10-28-21-23-34-507_com.google.android.googlequicksearchbox-edit.jpg](https://github.com/user-attachments/assets/5d96350c-c78e-425e-857b-7e30253b2909)

**Comment by QuarkBS2** [comment]
Hi, I would like to help with this

**Comment by TheBaljitSingh** [comment]
> Hi, I would like to help with this

Great 👍
